### ISSUE TITLE
build-libwebrtc issue

### ISSUE THREAD

**Issue by km147** [common-tater/wkwebview-webrtc-shim#1]
The build-libwebrtc tool causes the following error:

*_**-MBP:~ *__$ /Users/_**_/**_*****_/bin/build-libwebrtc ; exit;
/Users/**_***_/**_***_/wkwebview-webrtc-shim/bin/build-libwebrtc: line 80: fetch: command not found
/Users/**_***_/**_***_/wkwebview-webrtc-shim/bin/build-libwebrtc: line 83: cd: src: No such file or directory
error: pathspec '44' did not match any file(s) known to git.
fatal: Cannot update paths and switch to branch '44' at the same time.
Did you intend to checkout 'build/refs/remotes/branch-heads/44' which can not be resolved as commit?
fatal: bad object f421bdc68dbf8ab456d36909185b6b2a8935bc64
fatal: bad object b19eba3d4bbc70ece91d524e21e2e9d4253ff7a9
/Users/**_***_/**_****/wkwebview-webrtc-shim/bin/build-libwebrtc: line 105: gclient: command not found
logout

[Process completed]

**Comment by jessetane** [comment]
@km147 you need depot_tools!

https://www.chromium.org/developers/how-tos/install-depot-tools

I'll add a note to the docs, thanks for letting me know!

**Comment by jessetane** [comment]
The script should exit now if gclient is not in your PATH:

https://github.com/common-tater/wkwebview-webrtc-shim/blob/master/bin/build-libwebrtc#L71
