### ISSUE TITLE
Problem is Swift

### ISSUE THREAD

**Issue by julienkermarec** [common-tater/wkwebview-webrtc-shim#2]
Undefined symbols for architecture arm64:
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      webrtc::H264VideoToolboxEncoder::ConfigureCompressionSession() in libWebRTC.a(webrtc_h264_video_toolbox.h264_video_toolbox_encoder.o)

and 15 other errors.

**Comment by jessetane** [comment]
My first guess would be that we now need to include the VideoToolbox framework - does that fix anything for you?

**Comment by julienkermarec** [comment]
Ok, thanks, build succeed.

But your webView not work with PeerJS :(

**Comment by jessetane** [comment]
Check out https://github.com/feross/simple-peer

**Comment by jessetane** [comment]
Keep in mind this shim only works for data channels, so no voice or video.

**Comment by jessetane** [comment]
Also, if you feel up to it, you should submit a PR to fix the docs so others don't run into this issue!

**Comment by julienkermarec** [comment]
ok, i use PeerJs for audio.

**Comment by julienkermarec** [comment]
I hope Apple release this safari webrtc version soon :)

**Comment by jessetane** [comment]
Hah, me too!

**Comment by jessetane** [comment]
It's definitely possible to tunnel audio over data channels with https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder, but native support would indeed be better.
